//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlombukettenOnline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Boquetts = new HashSet<Boquett>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Comment { get; set; }
        public Nullable<int> EmailId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Boquett> Boquetts { get; set; }
        public virtual Email Email { get; set; }
    }
}
