//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlombukettenOnlineAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Boquetts = new HashSet<Boquett>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AddressId { get; set; }
        public decimal TotalPrice { get; set; }
        public string Comment { get; set; }
        public int EmailId { get; set; }
        public bool IsDelivered { get; set; }
        public int PaymentId { get; set; }
        public int DeliveryId { get; set; }
        public int StoreId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Boquett> Boquetts { get; set; }
        public virtual DeliveryMethod DeliveryMethod { get; set; }
        public virtual Email Email { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Store Store { get; set; }
    }
}
